# Generated by Django 2.2.16 on 2024-03-18 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я]*$', 'В логине только буквы допустимы.')], verbose_name='Логин'),
        ),
    ]
